services:
  ibf-db:
    container_name: ibf-db
    image: 'postgis/postgis:14-3.4'
    init: true
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DBNAME}
    volumes:
      - './postgresql.conf:/etc/postgresql.conf'
      - './init.sql:/docker-entrypoint-initdb.d/init.sql'
    ports:
      - '5436:5432'
    restart: unless-stopped
    healthcheck:
      test:
        [
          'CMD-SHELL',
          "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DBNAME}'",
        ]
      interval: 10s
      timeout: 3s
      retries: 3

  api-service:
    container_name: api-service
    build:
      context: api-service
      target: production
    init: true
    env_file: .env
    environment:
      - GLOBAL_IBF_VERSION
    ports:
      - '${PORT_API_SERVICE}:${PORT_API_SERVICE}'
    stdin_open: true
    tty: true
    depends_on:
      ibf-db:
        condition: service_healthy
        required: true
        restart: true
    restart: on-failure
    healthcheck:
      test:
        [
          'CMD',
          'curl',
          '-f',
          'http://localhost:${PORT_API_SERVICE}/api/instance/health',
        ]
      interval: 10s
      timeout: 5s
      retries: 10

  # Map vector tile service
  pg_tileserv:
    image: pramsey/pg_tileserv:20250131
    container_name: pg_tileserv
    platform: linux/amd64
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@ibf-db/${POSTGRES_DBNAME}
    depends_on:
      ibf-db:
        condition: service_healthy
    ports:
      - '7800:7800'

  # Map vector and point data service
  pg_featureserv:
    image: pramsey/pg_featureserv:20250917
    container_name: pg_featureserv
    platform: linux/amd64
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@ibf-db/${POSTGRES_DBNAME}
      PGFS_DATABASE_FUNCTIONINCLUDES: postgisftw
      PGFS_SERVER_DEBUG: ${PGFS_SERVER_DEBUG}
    volumes:
      - ./settings/pg_featureserv.json:/config.json:ro
    command: ["--config", "/config.json"]
    depends_on:
      ibf-db:
        condition: service_healthy
    ports:
      - '9000:9000'
