# See: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: 'Deploy [test] All'

permissions:
  actions: read
  deployments: write

on:
  workflow_call:
  workflow_dispatch:

jobs:
  deploy_service:
    name: 'Build + Deploy: api-service'
    uses: ./.github/workflows/deploy_test_api-service.yml
    secrets:
      AZURE_WEBAPP_PUBLISH_PROFILE: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
