# See: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: 'Test: Python quality (python-knip)'

on:
  workflow_dispatch:
  merge_group:
    types: [checks_requested]
  pull_request:
    paths:
      - '.github/workflows/test_formatting_python.yml'
      - '**/*.py'

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    defaults:
      run:
        working-directory: data

    steps:
      - name: Check code formatting
        id: formatting
        continue-on-error: true
        uses: omnilib/ufmt@action-v1
        with:
          path: '**/*.py'
          python-version: '3.12'

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gdal-bin libgdal-dev

      - name: Set up uv
        uses: astral-sh/setup-uv@v6

      - name: Install dependencies
        run: ./uv-sync.sh

      - name: Run python-knip
        id: python_knip
        continue-on-error: true
        run: uv run python-knip

      - name: Fail if any check failed
        if: always()
        run: |
          if [[ "${{ steps.formatting.outcome }}" == "failure" || "${{ steps.python_knip.outcome }}" == "failure" ]]; then
            echo "One or more checks failed. See above for details."
            exit 1
          fi
